include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: 3.1.4-dev.1

analyzer:
  exclude:
    - vendor/code_forge/**
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120

linter:
  rules:
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
